/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f6c14d7a-2e75-47fb-ad40-9c63fe034f8d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_FG6Q1EAdP",
    "aws_user_pools_web_client_id": "7ojsjgn0l16elspeshu4d93sqs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://szym2gafznas3cjvbjfavfomg4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-i2efpwa2qzac7lhysyeeikflz4"
};


export default awsmobile;
